service:
  name: ${self:custom.serviceName}
  awsKmsKeyArn: ${self:custom.kmsKeyArn}

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    secret: ${s3:${self:custom.serviceName}-${self:custom.stage}-secrets/servicePassword}
    foobar: ${s3:${self:custom.serviceName}-${self:custom.stage}-secrets/foobarKey}

custom:
  serviceName: fii-sls
  stage: ${opt:stage, file(./config/envVars.js):getEnvVariables.STAGE}
  accountId: ${file(./config/envVars.js):getEnvVariables.AWS_ACCOUNT_ID}
  kmsKeyArn: ${file(./config/envVars.js):getEnvVariables.AWS_KMS_KEY_ARN}

functions:
  hello:
    handler: src/handlers/authorizer/index.default

plugins:
  - serverless-webpack
  - serverless-offline
