service:
  name: ${self:custom.serviceName}

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    foobarKey: ${file(${self:custom.secrets}).foobarKey}

custom:
  serviceName: fii-sls
  stage: ${opt:stage, self:custom.defaultStage}
  accountId: ${file(${self:custom.secrets}).AWS_ACCOUNT_ID}
  secrets: ${s3:${self:custom.serviceName}-${self:custom.stage}-secrets/env.yml}
  defaultStage: dev-1
  stages:
    - ${opt:stage}
    - integration
    - production

functions:
  hello:
    handler: src/handlers/authorizer/index.default

plugins:
  - serverless-webpack
  - serverless-offline
