service:
  name: ${self:custom.serviceName}

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:REGION}
  profile: ${env:PROFILE}
  environment:
    SECRET1: ${ssm:/${self:custom.serviceName}/${env:STAGE}/onekey~true}

custom:
  serviceName: fii-sls
  stage: ${opt:stage, self:custom.defaultStage}
  defaultStage: dev
  stages:
    - ${opt:stage}
    - dev
    - integration
    - production

functions:
  hello:
    handler: src/handlers/authorizer/index.default
    events:
      - http:
          path: /slshello
          method: get

plugins:
  - serverless-webpack
  - serverless-offline
