service:
  name: ${self:custom.serviceName}
  awsKmsKeyArn: ${self:custom.kmsKeyArn}

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    secret: ${file(./config/envVars.js):getEnvVariables.FOO}
    foobar: ${file(./config/envVars.js):getEnvVariables.BAR}

# ${s3:${self:custom.serviceName}-${opt:stage}-secrets/

custom:
  serviceName: fii-sls
  accountId: ${file(./config/envVars.js):getEnvVariables.AWS_ACCOUNT_ID}
  kmsKeyArn: ${file(./config/envVars.js):getEnvVariables.AWS_KMS_KEY_ARN}

functions:
  hello:
    handler: src/handlers/authorizer/index.default

plugins:
  - serverless-webpack
  - serverless-offline
