service:
  name: ${self:custom.serviceName}

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:REGION}
  profile: ${env:PROFILE}
  environments:
    GLOBAL_SECRET: ${ssm:/${self:custom.serviceName}/${env:STAGE}/onekey~true}

custom:
  serviceName: fii-sls
  stage: ${opt:stage, self:custom.defaultStage}
  defaultStage: dev
  stages:
    - ${opt:stage}
    - dev
    - integration
    - production

functions:
  hello:
    handler: src/handlers/authorizer/index.default
    events:
      - http:
          path: /slshello
          method: get
    environment:
      HELLO_SECRET: ${ssm:/${self:custom.serviceName}/${env:STAGE}/onekey~true}
    layers:
      - arn:aws:lambda:us-east-1:568614285549:layer:dbconnection:1
