default_environment: &default_environment
    docker:
      - image: circleci/node:8.10
    working_directory: ~/fii-sls

version: 2
jobs:
  test:
    <<: *default_environment
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn test

  deploy_dev:
    <<: *default_environment
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - attach_workspace:
          at: workspace
      - run: >
             yarn global add serverless
             yarn deploy

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - deploy_dev:
          requires:
            - test
          filters:
            branches:
              only:
                - master
